In [1]:
import pandas as pd 
import numpy as np
from tensorflow import keras

In [22]:
f = open('data.txt', 'r')
lst = []
lst2 = []
board = []
count = 0
sumCount = 0
print(f)
index = 0
for line in f:
    index += 1
    arr = line.split()
    if len(arr) != 5:
        if len(arr) != 2:
            print(index)
        for i in range(sumCount):
            lst2.append([int(x) for x in arr])
        sumCount = 0
        continue
    board.append([int(x) for x in line.split()])
    count += 1
    if count == 5: 
        lst.append(board)
        count = 0
        board = []
        sumCount += 1



<_io.TextIOWrapper name='data.txt' mode='r' encoding='cp1252'>


In [16]:
for x in lst:
    print(type(x))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'li

In [31]:
print(len(lst), len(lst2))
for x in lst2:
    if x[0] == -1:
        x[0] = 0
    if x[1] == -1:
        x[1] = 0

12065 12065


In [32]:
trainData = np.array(lst)
trainOut = np.array(lst2)

print(trainData.shape, trainOut.shape)


(12065, 5, 5) (12065, 2)


In [33]:
print(trainOut.shape, trainData.shape)
print(trainOut)

(12065, 2) (12065, 5, 5)
[[1 0]
 [1 0]
 [1 0]
 ...
 [0 1]
 [0 1]
 [0 1]]


In [34]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from keras.layers.convolutional import Conv2D, MaxPooling2D,Conv1D, MaxPooling1D
from keras.layers import Flatten, BatchNormalization

In [35]:
model = Sequential()

model.add(Conv2D(filters=64, kernel_size=1, activation='relu', input_shape= (5,5,1)))
model.add(MaxPooling2D())
model.add(Conv2D(filters=24, kernel_size=1, activation='relu'))
model.add(MaxPooling2D())
model.add(Conv2D(filters=10, kernel_size=1, activation='relu'))
model.add(Flatten())
model.add(BatchNormalization())
model.add(Dense(2, activation = "softmax"))

model.compile(optimizer= 'adam', loss= 'mse', metrics= ['accuracy'])

In [36]:
model.fit(trainData, trainOut, epochs= 100, batch_size= 32)

Epoch 1/100
378/378 [==============================] - 1s 1ms/step - loss: 0.2502 - accuracy: 0.5412
Epoch 2/100
378/378 [==============================] - 1s 1ms/step - loss: 0.2468 - accuracy: 0.5455
Epoch 3/100
378/378 [==============================] - 1s 1ms/step - loss: 0.2465 - accuracy: 0.5444
Epoch 4/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2475 - accuracy: 0.5506
Epoch 5/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2462 - accuracy: 0.5515
Epoch 6/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2464 - accuracy: 0.5510
Epoch 7/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2463 - accuracy: 0.5498
Epoch 8/100
378/378 [==============================] - 1s 1ms/step - loss: 0.2462 - accuracy: 0.5521
Epoch 9/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2461 - accuracy: 0.5492
Epoch 10/100
378/378 [==============================] - 1s 2ms/step - loss: 0.2460 - accura

In [37]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 5, 5, 64)          128       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 2, 2, 64)         0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 2, 2, 24)          1560      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 1, 1, 24)         0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 1, 1, 10)          250       
                                                                 
 flatten_1 (Flatten)         (None, 10)               

In [39]:
temp = np.expand_dims(trainData[60], 0)
temp = np.expand_dims(temp, -1)
print(temp.shape)
model.predict(temp)

(1, 5, 5, 1)
1/1 [==============================] - 0s 17ms/step


array([[0.51514935, 0.48485062]], dtype=float32)

In [49]:
model.save_weights('f.h5')

In [80]:
model = Sequential([
    Dense(64, activation = 'relu', input_shape = (25, )),
    Dense(4, activation = 'relu')
])

model.load_weights('chess.h5')

In [81]:
model.predict(trainData[0].reshape((1,-1)))

1/1 [==============================] - 0s 49ms/step


array([[0.        , 0.12819847, 0.72067577, 0.9626852 ]], dtype=float32)